version: '3'
services:
  automate1:
    image: automate:1.1
    container_name: automate1
    restart: always 
    hostname: "1"
    depends_on:
      - workerServer 
    networks:
      - usine_network 
  automate2:
    image: automate:1.1
    container_name: automate2
    restart: always 
    hostname: "2"
    depends_on:
      - workerServer 
    networks:
      - usine_network
  automate3:
    image: automate:1.1
    container_name: automate3
    restart: always 
    hostname: "3"
    depends_on:
      - workerServer 
    networks:
      - usine_network
  automate4:
    image: automate:1.1
    container_name: automate4
    restart: always 
    hostname: "4"
    depends_on:
      - workerServer
    networks:
      - usine_network 
  automate5:
    image: automate:1.1
    container_name: automate5
    restart: always
    hostname: "5"
    depends_on:
      - workerServer        
    networks:
      - usine_network
  workerServer:
    image: workerserver:1.0    
    container_name: workerServer
    restart: always
    hostname: "workerserver"
    networks:
      usine_network:
        ipv4_address: 172.30.0.10
    

networks:
  usine_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
          #    gateway: 172.30.0.1
